CREATE TABLE IF NOT EXISTS comanda_menu.product (
	product_id	INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	product_name 	VARCHAR(30) NOT NULL,
	price		FLOAT NOT NULL,
	category	VARCHAR(15) NOT NULL,
	description 	VARCHAR(100) DEFAULT NULL,
	stock		INTEGER DEFAULT 0,
	image		MEDIUMBLOB DEFAULT NULL,
	created_at	DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at	DATETIME ON UPDATE CURRENT_TIMESTAMP
);
